import useStore from '../../hooks/useStore';

import EditTags from './';

function Template({tags}) {
	// need selectedPodcast from useStore because key (generated by nanoid) would not match otherwise
	const selectedPodcast = useStore(state => state.selectedPodcast);
	return <EditTags selectedPodcast={selectedPodcast} tags={tags} />;
}

export const Default = Template.bind({});

Default.args = {
	tags: [
		'news',
		'web development',
		'art',
		'tech',
		'history',
		'comedy',
		'politics',
		'science',
		'sports',
		'health',
	],
};

const story = {
	title: 'EditTags',
	component: EditTags,
};

export default story;
