import useStore from '../../hooks/useStore';

import EditTags from './';

function Template() {
	// need selectedPodcast from useStore because key (generated by nanoid) would not match otherwise
	const selectedPodcast = useStore(state => state.podcasts[0]);
	return <EditTags selectedPodcast={selectedPodcast} />;
}

export const Default = Template.bind({});

const story = {
	title: 'EditTags',
	component: EditTags,
	decorators: [
		Story => (
			<div
				style={{
					display: 'flex',
					flexDirection: 'column',
					gap: '0.8rem',
				}}
			>
				<Story />
			</div>
		),
	],
};

export default story;
